image: nixos/nix:latest

#  launches NixOS in a docker image; runs nix-build default.nix and 
#  collects all build tgz files as build artifacts. These can be downloaded.

build-all:
  stage: build
  script:
   - nix-build -k default.nix
   - RET=$?
   - find -L result* -type f -name '*.tgz' -exec cp '{}' . '+'
   - (exit $RET)
  artifacts:
    paths:
      - "*.tgz"
    when: always
    expire_in: 1 week
