image: nixos/nix:latest

stages:
 - build_test
 - results

.tmpl:
  stage: build_test
  script:
    - nix-build with-cmake.nix -A $TARGET
    - mkdir $TARGET
    - mv result/* $TARGET/
  artifacts:
    paths:
    - $TARGET
    when: always
    expire_in: 1 week

linux-x86:
  extends: .tmpl
  variables:
    TARGET: linux-x86

linux-makecontext:
  extends: .tmpl
  variables:
    TARGET: linux-makecontext

posix:
  extends: .tmpl
  variables:
    TARGET: posix

coverage:
  stage: results
  variables:
    GIT_STRATEGY: none
  script:
    - ls -la
