image: nixos/nix:latest

.tmpl:
  stage: build
  script:
    - nix-build with-cmake.nix -A $TARGET
  artifacts:
    paths:
    - result/coverage.info
    - result/test-report.txt
    when: always
    expire_in: 1 week

linux-x86:
  extends: .tmpl
  variables:
    TARGET: linux-x86

linux-makecontext:
  extends: .tmpl
  variables:
    TARGET: linux-makecontext

posix:
  extends: .tmpl
  variables:
    TARGET: posix
